# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.5
  - 3.6
  - release
os:
  - linux
  dist:
    - bionic
  - osx
cache: packages
warnings_are_errors: true
branches:
  only:
   - master
