# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.6
  - release
os:
  - osx
  - linux
  - windows
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      
branches:
  only:
   - master
