# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
os:
  - osx
dist:
  - xenial
cache: packages
warnings_are_errors: true
branches:
  only:
   - master
