# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.5
  - 3.6
  - release
  - devel
os:
  - linux
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

branches:
  only:
   - master

after_success:
- Rscript -e 'covr::codecov()'
